<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Laraue.Apps.MarkdownTranspiler.WebApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2"/>
        <PackageReference Include="Scalar.AspNetCore" Version="$(ScalarVersion)" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Laraue.Apps.MarkdownUtils.Services\Laraue.Apps.MarkdownUtils.Services.csproj" />
    </ItemGroup>

</Project>
