<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <ProjectReference Include="..\Laraue.Apps.MarkdownUtils.Contracts\Laraue.Apps.MarkdownUtils.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Laraue.Core.Exceptions" Version="10.3.1" />
    <PackageReference Include="Laraue.Interpreter.Markdown" Version="$(LaraueMarkdownInterpreterVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>
  
</Project>
