# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Run all tests
      run: dotnet test -c Release --no-build

    - name: Pack Web API Host
      if: github.ref == 'refs/heads/main'
      run: tar -czf webapi-host.tar.gz -C src/Laraue.Apps.MarkdownUtils.WebApiHost/bin/Release/net10.0 .

    - name: Upload Web API Host
      if: github.ref == 'refs/heads/main'
      uses: marcodallasanta/ssh-scp-deploy@v1.2.0
      with:
       host: ${{ secrets.SSH_HOST }} # "example.com"
       port: ${{ secrets.SSH_PORT }} # 22
       user: ${{ secrets.SSH_USER }} # "user"
       password: ${{ secrets.SSH_PASSWORD }} # "password"
       local: webapi-host.tar.gz
       remote: "/home/laraue/markdown-utils-web-api-host"
       post_upload:
        cd /home/laraue/markdown-utils-web-api-host && find . -mindepth 1 ! -name webapi-host.tar.gz -delete &&
        tar -xzf webapi-host.tar.gz && rm webapi-host.tar.gz
